name: ✨ Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        We love feature requests!

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Trading Analysis
        - Data Integration
        - User Interface
        - API/Webhooks
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
    validations:
      required: true
